name = "JSOSolverSkeleton"
uuid = "c81ce882-e686-4888-976a-ce42bb892d34"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"

[compat]
NLPModels = "0.20"
SolverCore = "0.3"
